"""add timezone to users

Revision ID: 63abd0163094
Revises: 98ddf891fc68
Create Date: 2026-05-14 12:25:01.917789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63abd0163094'
down_revision: Union[str, Sequence[str], None] = '98ddf891fc68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.String(length=64), server_default='Europe/Moscow', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
