"""create subscription reminders table

Revision ID: 98ddf891fc68
Revises: a51b5dcea899
Create Date: 2026-05-13 22:47:31.175949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ddf891fc68'
down_revision: Union[str, Sequence[str], None] = 'a51b5dcea899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_reminders',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('days_left', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_subscription_reminders_remind_at'), 'subscription_reminders', ['remind_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_reminders_remind_at'), table_name='subscription_reminders')
    op.drop_table('subscription_reminders')
    # ### end Alembic commands ###
